spring:
  datasource:
    url: jdbc:h2:mem:test
    username: admin
    password:
#      url: jdbc:mysql://localhost:3306/serwis?useSSL=false&serverTimezone=Europe/Warsaw&allowPublicKeyRetrieval=true
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      username: root
#      password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  liquibase:
    change-log: classpath:db/master.xml
